---
services:
  cron-tg:
    image: docker.io/vsuh/cron-tg:latest
    container_name: cron-tg
    ports:
      - "7878:7999"
    environment:
      - UUID=appuser
    volumes:
      - /opt/cron-reminder/env/.env.prod:/workspaces/cron-tg-docker/.env
      - /opt/cron-reminder/log:/workspaces/cron-tg-docker/log
      - /opt/cron-reminder/db:/workspaces/cron-tg-docker/db
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
      - "diun.include_tags=^v[0-9]+\\.[0-9]+\\.[0-9]+$"
      - "diun.notify_on=new;update"
      - "diun.hub.link=https://hub.docker.com/repository/docker/vsuh/cron-tg/tags"
